sonar.projectKey=Exohayvan_Continuum
sonar.organization=exohayvan

# This is the name displayed in the SonarQube Cloud UI.
sonar.projectName=Continuum

# Paths are relative to this file.
sonar.sources=main.go,src
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,build/**,src/frontend/wailsjs/**,continuum
sonar.coverage.exclusions=src/frontend/**,build/**
sonar.go.coverage.reportPaths=coverage.out

# Encoding of the source code. Default is default system encoding.
sonar.sourceEncoding=UTF-8
